"""Phone Call Tool — Make automated phone calls via Twilio.

SPESION can call companies (Endesa, banks, ISPs, etc.) on your behalf using
Twilio's Programmable Voice API.  The call uses a TwiML script generated by
the LLM that guides the conversation, and the call audio is recorded for
your review.

Requires:
  pip install twilio
  .env:
    TWILIO_ACCOUNT_SID=AC...
    TWILIO_AUTH_TOKEN=...
    TWILIO_PHONE_NUMBER=+34...     (your Twilio number)
    YOUR_PHONE_NUMBER=+34...       (your real number for callbacks)
"""

from __future__ import annotations

import logging
from typing import Any

from langchain_core.tools import tool

logger = logging.getLogger(__name__)

# ─── Lazy Twilio client ──────────────────────────────────────────────────────

_twilio_client = None


def _get_twilio():
    """Return a configured Twilio Client singleton."""
    global _twilio_client
    if _twilio_client is not None:
        return _twilio_client

    try:
        from twilio.rest import Client
    except ImportError:
        raise RuntimeError(
            "twilio package not installed.  Run: pip install twilio"
        )

    from src.core.config import settings
    sid = getattr(settings, "twilio_account_sid", None)
    token = getattr(settings, "twilio_auth_token", None)
    if not sid or not token:
        raise RuntimeError(
            "TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN must be set in .env"
        )

    sid_val = sid.get_secret_value() if hasattr(sid, "get_secret_value") else str(sid)
    token_val = token.get_secret_value() if hasattr(token, "get_secret_value") else str(token)
    _twilio_client = Client(sid_val, token_val)
    return _twilio_client


def _get_twilio_phone() -> str:
    """Return the outbound Twilio phone number from settings."""
    from src.core.config import settings
    num = getattr(settings, "twilio_phone_number", None)
    if not num:
        raise RuntimeError("TWILIO_PHONE_NUMBER not set in .env")
    return str(num)


def _get_callback_url() -> str | None:
    """Return the public callback URL for status updates, if configured."""
    from src.core.config import settings
    return getattr(settings, "twilio_callback_url", None)


# ─── Tools ────────────────────────────────────────────────────────────────────

@tool
def make_phone_call(
    to_number: str,
    purpose: str,
    script: str,
    language: str = "es-ES",
    record: bool = True,
) -> dict[str, Any]:
    """Make an automated phone call to a company or person on behalf of the user.

    ⚠️ DANGEROUS — requires user approval before execution.

    Args:
        to_number: Full phone number including country code (e.g. +34900123456)
        purpose: One-line summary of WHY we're calling (for logs)
        script: The text-to-speech script SPESION will say when the call connects.
                Keep it professional, clear, and concise.  Example:
                "Hola, llamo en nombre de Eric González respecto a la factura
                 número 12345 que contiene un cargo incorrecto de 47€ en el
                 concepto de gas.  Solicito la revisión y corrección."
        language: BCP-47 language code for TTS (default: es-ES)
        record: Whether to record the call (default: True)

    Returns:
        Dict with call_sid, status, and recording info.
    """
    client = _get_twilio()
    from_number = _get_twilio_phone()
    callback_url = _get_callback_url()

    # Build TwiML
    twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Say voice="Polly.Lucia" language="{language}">{_escape_xml(script)}</Say>
    <Pause length="2"/>
    <Say voice="Polly.Lucia" language="{language}">Si necesita responder, por favor hable después del tono.</Say>
    <Record maxLength="120" playBeep="true" transcribe="true" timeout="5"/>
    <Say voice="Polly.Lucia" language="{language}">Gracias por su tiempo. Un saludo.</Say>
</Response>"""

    try:
        call_params: dict[str, Any] = {
            "to": to_number,
            "from_": from_number,
            "twiml": twiml,
        }
        if record:
            call_params["record"] = True
        if callback_url:
            call_params["status_callback"] = callback_url
            call_params["status_callback_event"] = ["initiated", "ringing", "answered", "completed"]

        call = client.calls.create(**call_params)

        logger.info(f"📞 Call initiated: SID={call.sid}, to={to_number}, purpose={purpose}")
        return {
            "call_sid": call.sid,
            "status": call.status,
            "to": to_number,
            "from": from_number,
            "purpose": purpose,
            "message": f"Call initiated to {to_number}. SID: {call.sid}",
        }

    except Exception as e:
        logger.error(f"Phone call failed: {e}")
        return {"error": str(e), "to": to_number, "purpose": purpose}


@tool
def check_call_status(call_sid: str) -> dict[str, Any]:
    """Check the status of a previously initiated phone call.

    Args:
        call_sid: The Call SID returned by make_phone_call.

    Returns:
        Dict with current status, duration, recording URL, etc.
    """
    client = _get_twilio()
    try:
        call = client.calls(call_sid).fetch()
        result: dict[str, Any] = {
            "call_sid": call.sid,
            "status": call.status,
            "direction": call.direction,
            "duration": call.duration,
            "start_time": str(call.start_time) if call.start_time else None,
            "end_time": str(call.end_time) if call.end_time else None,
            "to": call.to,
            "from": call.from_,
            "price": call.price,
            "price_unit": call.price_unit,
        }

        # Check for recordings
        recordings = client.recordings.list(call_sid=call_sid)
        if recordings:
            result["recordings"] = [
                {
                    "sid": r.sid,
                    "duration": r.duration,
                    "url": f"https://api.twilio.com/2010-04-01/Accounts/{client.username}/Recordings/{r.sid}.mp3",
                }
                for r in recordings
            ]

        return result

    except Exception as e:
        return {"error": str(e), "call_sid": call_sid}


@tool
def send_sms(
    to_number: str,
    message: str,
) -> dict[str, Any]:
    """Send an SMS message via Twilio.

    ⚠️ DANGEROUS — requires user approval before execution.

    Args:
        to_number: Full phone number including country code (e.g. +34612345678)
        message: The SMS body (max 1600 characters)

    Returns:
        Dict with message_sid and status.
    """
    client = _get_twilio()
    from_number = _get_twilio_phone()

    try:
        msg = client.messages.create(
            to=to_number,
            from_=from_number,
            body=message[:1600],
        )
        logger.info(f"📱 SMS sent: SID={msg.sid}, to={to_number}")
        return {
            "message_sid": msg.sid,
            "status": msg.status,
            "to": to_number,
            "body_preview": message[:80],
        }

    except Exception as e:
        logger.error(f"SMS failed: {e}")
        return {"error": str(e), "to": to_number}


# ─── Factory ──────────────────────────────────────────────────────────────────

def create_phone_tools() -> list:
    """Return all phone/SMS tools."""
    return [make_phone_call, check_call_status, send_sms]


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _escape_xml(text: str) -> str:
    """Escape special XML characters for TwiML."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )
